version: '3'
services:
    web-router: 
      build:
        context: ./
        dockerfile: Dockerfile
      restart: always
      ports:
        - "80:80"

    database:
      image: postgres:latest
      restart: always
      container_name: database
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password1
        POSTGRES_DB: rest_api
      ports:
        - "5432:5432"
      volumes:
        - ./restapi/db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
        - ./restapi/db/data.sql:/docker-entrypoint-initdb.d/2-data.sql

    frontend:
      build:
        context: ./react/
        dockerfile: Dockerfile
      restart: always
      container_name: frontend
      volumes:
          - ./react/build :/usr/share/nginx/html
      ports: 
        - "8080:8080"
      depends_on:
        - webapi
        - database
        - web-router

    webapi:
        image: golang:latest
        restart: always
        container_name: webapi
        ports:
          - "8081:8081"
        volumes:
          - ./restapi/go :/go/src/
        command: >
          sh -c " 
            apk update
            apk add git
            go get "github.com/gorilla/mux"
            go get "github.com/lib/pq"
            go run /go/src/main.go"
        depends_on:
          - database
          - web-router
        environment:
          DATABASE_HOST: database